---
- name: Destroy infrastructure on DigitalOcean
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/all.yml

  vars:
    droplet_names:
      - "{{ jenkins_name }}"
      - "{{ sonarqube_name }}"
      - "{{ nexus_name }}"

  tasks:
    - name: Sanity check required vars
      ansible.builtin.assert:
        that:
          - do_token is defined
          - droplet_names | length > 0
        fail_msg: "Missing do_token or droplet_names. Check group_vars/all.yml and your env (DO_TOKEN)."

    - name: Destroy droplets by unique name
      community.digitalocean.digital_ocean_droplet:
        state: absent
        name: "{{ item }}"
        unique_name: true
        oauth_token: "{{ do_token }}"
      loop: "{{ droplet_names }}"
      loop_control:
        label: "{{ item }}"

    - name: Summary
      ansible.builtin.debug:
        msg: "Requested destroy for droplets: {{ droplet_names | join(', ') }}."
