---
- name: Create Nexus data directory
  file:
    path: /opt/nexus-data
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Run Nexus3
  shell: |
    if [ ! "$(docker ps -q -f name=nexus)" ]; then
      docker run -d --name nexus --restart=unless-stopped         -p 8081:8081         -v /opt/nexus-data:/nexus-data         sonatype/nexus3
    fi