# -----------------------------
# Portainer CE (Docker UI) on 9443 (avoid SonarQube 9000 conflict)
# -----------------------------
- name: Create Portainer volume
  ansible.builtin.shell: docker volume create portainer_data
  register: portainer_vol
  changed_when: "'portainer_data' in portainer_vol.stdout"
  failed_when: false
  tags: [portainer]

# If an old portainer exists (bound to 9000), remove it so we can re-run cleanly
- name: Remove old Portainer container if present (was on :9000)
  ansible.builtin.shell: |
    if docker ps -a --format '{{"{{.Names}}"}}' | grep -qx portainer; then
      docker rm -f portainer || true
    fi
  changed_when: false
  failed_when: false
  tags: [portainer]

- name: Run Portainer CE on 9443 (idempotent)
  ansible.builtin.shell: |
    if [ ! "$(docker ps -q -f name=portainer)" ]; then
      docker run -d --name portainer --restart=always \
        -p 9443:9443 -p 8000:8000 \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v portainer_data:/data \
        portainer/portainer-ce
    fi
  changed_when: false
  failed_when: false
  tags: [portainer]
